/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.mikan.sample.mutton.network.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param identities メンバーのユーザーIDかチームに登録しているemailアドレスの一覧
 */
@Serializable

data class AddGroupMemberRequest (

    /* メンバーのユーザーIDかチームに登録しているemailアドレスの一覧 */
    @SerialName(value = "identities") @Required val identities: kotlin.collections.List<kotlin.String>

) {


}

