/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.mikan.sample.mutton.network.model

import io.github.mikan.sample.mutton.network.model.User

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 記事やプロジェクトに付けられたコメントを表します。プロジェクトへのコメントはQiita Teamでのみ有効です。
 *
 * @param body コメントの内容を表すMarkdown形式の文字列
 * @param createdAt データが作成された日時
 * @param id コメントの一意なID
 * @param renderedBody コメントの内容を表すHTML形式の文字列
 * @param updatedAt データが最後に更新された日時
 * @param user 
 */
@Serializable

data class Comment (

    /* コメントの内容を表すMarkdown形式の文字列 */
    @SerialName(value = "body") @Required val body: kotlin.String,

    /* データが作成された日時 */
    @SerialName(value = "created_at") @Required val createdAt: kotlin.String,

    /* コメントの一意なID */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* コメントの内容を表すHTML形式の文字列 */
    @SerialName(value = "rendered_body") @Required val renderedBody: kotlin.String,

    /* データが最後に更新された日時 */
    @SerialName(value = "updated_at") @Required val updatedAt: kotlin.String,

    @SerialName(value = "user") @Required val user: User

) {


}

