/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.mikan.sample.mutton.network.model

import io.github.mikan.sample.mutton.network.model.ItemTag

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param body Markdown形式の本文
 * @param tags 記事に付いたタグ一覧
 * @param title 記事のタイトル
 * @param coediting この記事が共同更新状態かどうか (Qiita Teamでのみ有効)
 * @param groupUrlName この投稿を公開するグループの url_name (null で全体に公開。Qiita Teamでのみ有効)
 * @param `private` 限定共有状態かどうかを表すフラグ (Qiita Teamでは無効)
 * @param tweet Twitterに投稿するかどうか (Twitter連携を有効化している場合のみ有効)
 * @param organizationUrlName 記事のOrganization の url_name を表します。
 * @param slide スライドモードが有効を表すフラグ
 */
@Serializable

data class CreateItemRequest (

    /* Markdown形式の本文 */
    @SerialName(value = "body") @Required val body: kotlin.String,

    /* 記事に付いたタグ一覧 */
    @SerialName(value = "tags") @Required val tags: kotlin.collections.List<ItemTag>,

    /* 記事のタイトル */
    @SerialName(value = "title") @Required val title: kotlin.String,

    /* この記事が共同更新状態かどうか (Qiita Teamでのみ有効) */
    @SerialName(value = "coediting") val coediting: kotlin.Boolean? = null,

    /* この投稿を公開するグループの url_name (null で全体に公開。Qiita Teamでのみ有効) */
    @SerialName(value = "group_url_name") val groupUrlName: kotlin.String? = null,

    /* 限定共有状態かどうかを表すフラグ (Qiita Teamでは無効) */
    @SerialName(value = "private") val `private`: kotlin.Boolean? = null,

    /* Twitterに投稿するかどうか (Twitter連携を有効化している場合のみ有効) */
    @SerialName(value = "tweet") val tweet: kotlin.Boolean? = null,

    /* 記事のOrganization の url_name を表します。 */
    @SerialName(value = "organization_url_name") val organizationUrlName: kotlin.String? = null,

    /* スライドモードが有効を表すフラグ */
    @SerialName(value = "slide") val slide: kotlin.Boolean? = null

) {


}

