/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.mikan.sample.mutton.network.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param urlName グループのチーム上での一意な名前を表します。
 * @param name グループに付けられた表示用の名前を表します。
 * @param `private` 非公開グループかどうかを表します。
 * @param description Qiita Teamのグループを表します。
 */
@Serializable

data class CreateGroupRequest (

    /* グループのチーム上での一意な名前を表します。 */
    @SerialName(value = "url_name") @Required val urlName: kotlin.String,

    /* グループに付けられた表示用の名前を表します。 */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* 非公開グループかどうかを表します。 */
    @SerialName(value = "private") @Required val `private`: kotlin.Boolean,

    /* Qiita Teamのグループを表します。 */
    @SerialName(value = "description") val description: kotlin.String? = null

) {


}

