/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.mikan.sample.mutton.network.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param body コメントの内容を表すMarkdown形式の文字列
 */
@Serializable

data class CreateCommentRequest (

    /* コメントの内容を表すMarkdown形式の文字列 */
    @SerialName(value = "body") @Required val body: kotlin.String

) {


}

