/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.mikan.sample.mutton.network.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param body コメントの内容を表すMarkdown形式の文字列
 * @param userId ユーザーID
 * @param createdAt データが作成された日時
 * @param updatedAt データが最後に更新された日時
 */
@Serializable

data class CreateImportedCommentRequest (

    /* コメントの内容を表すMarkdown形式の文字列 */
    @SerialName(value = "body") @Required val body: kotlin.String,

    /* ユーザーID */
    @SerialName(value = "user_id") @Required val userId: kotlin.String,

    /* データが作成された日時 */
    @SerialName(value = "created_at") val createdAt: kotlin.String? = null,

    /* データが最後に更新された日時 */
    @SerialName(value = "updated_at") val updatedAt: kotlin.String? = null

) {


}

