/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.mikan.sample.mutton.network.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param createdAt 
 * @param description 
 * @param name 
 * @param `private` 
 * @param updatedAt 
 * @param urlName 
 */
@Serializable

data class GetAuthenticatedUserItemsResponseInnerGroup (

    @SerialName(value = "created_at") val createdAt: kotlin.String? = null,

    @SerialName(value = "description") val description: kotlin.String? = null,

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "private") val `private`: kotlin.Boolean? = null,

    @SerialName(value = "updated_at") val updatedAt: kotlin.String? = null,

    @SerialName(value = "url_name") val urlName: kotlin.String? = null

) {


}

