/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.mikan.sample.mutton.network.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param name 
 * @param versions 
 */
@Serializable

data class GetAuthenticatedUserItemsResponseInnerTagsInner (

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "versions") val versions: kotlin.collections.List<kotlin.String>? = null

) {


}

