/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.mikan.sample.mutton.network.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param description 
 * @param facebookId 
 * @param followeesCount 
 * @param followersCount 
 * @param githubLoginName 
 * @param id 
 * @param itemsCount 
 * @param linkedinId 
 * @param location 
 * @param name 
 * @param organization 
 * @param permanentId 
 * @param profileImageUrl 
 * @param teamOnly 
 * @param twitterScreenName 
 * @param websiteUrl 
 */
@Serializable

data class GetAuthenticatedUserItemsResponseInnerUser (

    @SerialName(value = "description") val description: kotlin.String? = null,

    @SerialName(value = "facebook_id") val facebookId: kotlin.String? = null,

    @SerialName(value = "followees_count") val followeesCount: kotlin.Int? = null,

    @SerialName(value = "followers_count") val followersCount: kotlin.Int? = null,

    @SerialName(value = "github_login_name") val githubLoginName: kotlin.String? = null,

    @SerialName(value = "id") val id: kotlin.String? = null,

    @SerialName(value = "items_count") val itemsCount: kotlin.Int? = null,

    @SerialName(value = "linkedin_id") val linkedinId: kotlin.String? = null,

    @SerialName(value = "location") val location: kotlin.String? = null,

    @SerialName(value = "name") val name: kotlin.String? = null,

    @SerialName(value = "organization") val organization: kotlin.String? = null,

    @SerialName(value = "permanent_id") val permanentId: kotlin.Int? = null,

    @SerialName(value = "profile_image_url") val profileImageUrl: kotlin.String? = null,

    @SerialName(value = "team_only") val teamOnly: kotlin.Boolean? = null,

    @SerialName(value = "twitter_screen_name") val twitterScreenName: kotlin.String? = null,

    @SerialName(value = "website_url") val websiteUrl: kotlin.String? = null

) {


}

