/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.mikan.sample.mutton.network.model

import io.github.mikan.sample.mutton.network.model.GetAuthenticatedUserItemsResponseInnerGroup
import io.github.mikan.sample.mutton.network.model.GetAuthenticatedUserItemsResponseInnerTagsInner
import io.github.mikan.sample.mutton.network.model.GetAuthenticatedUserItemsResponseInnerTeamMembership
import io.github.mikan.sample.mutton.network.model.GetAuthenticatedUserItemsResponseInnerUser

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param renderedBody 
 * @param body 
 * @param coediting 
 * @param commentsCount 
 * @param createdAt 
 * @param group 
 * @param id 
 * @param likesCount 
 * @param `private` 
 * @param reactionsCount 
 * @param stocksCount 
 * @param tags 
 * @param title 
 * @param updatedAt 
 * @param url 
 * @param user 
 * @param pageViewsCount 
 * @param teamMembership 
 * @param organizationUrlName 
 * @param slide 
 */
@Serializable

data class GetAuthenticatedUserItemsResponseInner (

    @SerialName(value = "rendered_body") val renderedBody: kotlin.String? = null,

    @SerialName(value = "body") val body: kotlin.String? = null,

    @SerialName(value = "coediting") val coediting: kotlin.Boolean? = null,

    @SerialName(value = "comments_count") val commentsCount: kotlin.Int? = null,

    @SerialName(value = "created_at") val createdAt: kotlin.String? = null,

    @SerialName(value = "group") val group: GetAuthenticatedUserItemsResponseInnerGroup? = null,

    @SerialName(value = "id") val id: kotlin.String? = null,

    @SerialName(value = "likes_count") val likesCount: kotlin.Int? = null,

    @SerialName(value = "private") val `private`: kotlin.Boolean? = null,

    @SerialName(value = "reactions_count") val reactionsCount: kotlin.Int? = null,

    @SerialName(value = "stocks_count") val stocksCount: kotlin.Int? = null,

    @SerialName(value = "tags") val tags: kotlin.collections.List<GetAuthenticatedUserItemsResponseInnerTagsInner>? = null,

    @SerialName(value = "title") val title: kotlin.String? = null,

    @SerialName(value = "updated_at") val updatedAt: kotlin.String? = null,

    @SerialName(value = "url") val url: kotlin.String? = null,

    @SerialName(value = "user") val user: GetAuthenticatedUserItemsResponseInnerUser? = null,

    @SerialName(value = "page_views_count") val pageViewsCount: kotlin.Int? = null,

    @SerialName(value = "team_membership") val teamMembership: GetAuthenticatedUserItemsResponseInnerTeamMembership? = null,

    @SerialName(value = "organization_url_name") val organizationUrlName: kotlin.String? = null,

    @SerialName(value = "slide") val slide: kotlin.Boolean? = null

) {


}

