/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.mikan.sample.mutton.network.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * Qiita Teamのグループを表します。
 *
 * @param createdAt データが作成された日時
 * @param description グループの詳細を表します。
 * @param name グループに付けられた表示用の名前を表します。
 * @param `private` 非公開グループかどうかを表します。
 * @param updatedAt データが最後に更新された日時
 * @param urlName グループのチーム上での一意な名前を表します。
 */
@Serializable

data class Group (

    /* データが作成された日時 */
    @SerialName(value = "created_at") @Required val createdAt: kotlin.String,

    /* グループの詳細を表します。 */
    @SerialName(value = "description") @Required val description: kotlin.String,

    /* グループに付けられた表示用の名前を表します。 */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* 非公開グループかどうかを表します。 */
    @SerialName(value = "private") @Required val `private`: kotlin.Boolean,

    /* データが最後に更新された日時 */
    @SerialName(value = "updated_at") @Required val updatedAt: kotlin.String,

    /* グループのチーム上での一意な名前を表します。 */
    @SerialName(value = "url_name") @Required val urlName: kotlin.String

) {


}

