/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.mikan.sample.mutton.network.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param clientId 登録されたAPIクライアントを特定するためのID
 * @param clientSecret 登録されたAPIクライアントを認証するための秘密鍵
 * @param code リダイレクト用のURLに付与された、アクセストークンと交換するための文字列
 */
@Serializable

data class IssueAccessTokenRequest (

    /* 登録されたAPIクライアントを特定するためのID */
    @SerialName(value = "client_id") @Required val clientId: kotlin.String,

    /* 登録されたAPIクライアントを認証するための秘密鍵 */
    @SerialName(value = "client_secret") @Required val clientSecret: kotlin.String,

    /* リダイレクト用のURLに付与された、アクセストークンと交換するための文字列 */
    @SerialName(value = "code") @Required val code: kotlin.String

) {


}

