/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.mikan.sample.mutton.network.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param clientId 登録されたAPIクライアントを特定するためのID
 * @param scopes アクセストークンに許された操作の一覧
 * @param token アクセストークンを表現する文字列
 */
@Serializable

data class IssueAccessTokenResponse (

    /* 登録されたAPIクライアントを特定するためのID */
    @SerialName(value = "client_id") @Required val clientId: kotlin.String,

    /* アクセストークンに許された操作の一覧 */
    @SerialName(value = "scopes") @Required val scopes: kotlin.collections.List<kotlin.String>,

    /* アクセストークンを表現する文字列 */
    @SerialName(value = "token") @Required val token: kotlin.String

) {


}

