/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.mikan.sample.mutton.network.model


import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param name タグ名
 * @param versions バージョン
 */
@Serializable

data class ItemTag (

    /* タグ名 */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* バージョン */
    @SerialName(value = "versions") @Required val versions: kotlin.collections.List<kotlin.String>

) {


}

