/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.mikan.sample.mutton.network.model

import io.github.mikan.sample.mutton.network.model.User

import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

/**
 * 
 *
 * @param createdAt データが作成された日時
 * @param user 
 */
@Serializable

data class LikeHistory (

    /* データが作成された日時 */
    @SerialName(value = "created_at") @Required val createdAt: kotlin.String,

    @SerialName(value = "user") @Required val user: User

) {


}

