/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package io.github.mikan.sample.mutton.network.remote

import io.github.mikan.sample.mutton.network.model.AddGroupMemberRequest
import io.github.mikan.sample.mutton.network.model.AuthenticatedUser
import io.github.mikan.sample.mutton.network.model.Comment
import io.github.mikan.sample.mutton.network.model.CreateCommentRequest
import io.github.mikan.sample.mutton.network.model.CreateGroupRequest
import io.github.mikan.sample.mutton.network.model.CreateImportedCommentRequest
import io.github.mikan.sample.mutton.network.model.CreateItemRequest
import io.github.mikan.sample.mutton.network.model.DeleteGroupMemberRequest
import io.github.mikan.sample.mutton.network.model.Group
import io.github.mikan.sample.mutton.network.model.GroupMember
import io.github.mikan.sample.mutton.network.model.Item
import io.github.mikan.sample.mutton.network.model.UpdateCommentRequest
import io.github.mikan.sample.mutton.network.model.UpdateGroupRequest
import io.github.mikan.sample.mutton.network.model.UpdateItemRequest
import io.github.mikan.sample.mutton.network.model.User

import io.github.mikan.sample.mutton.network.infrastructure.*
import io.ktor.client.HttpClient
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import kotlinx.serialization.json.Json
import io.ktor.http.ParametersBuilder
import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*

open class TeamApi : ApiClient {

    constructor(
        baseUrl: String = ApiClient.BASE_URL,
        httpClientEngine: HttpClientEngine? = null,
        httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
        jsonSerializer: Json = ApiClient.JSON_DEFAULT
    ) : super(baseUrl = baseUrl, httpClientEngine = httpClientEngine, httpClientConfig = httpClientConfig, jsonBlock = jsonSerializer)

    constructor(
        baseUrl: String,
        httpClient: HttpClient
    ): super(baseUrl = baseUrl, httpClient = httpClient)

    /**
     * Add group members
     * 新たにグループにメンバーを追加します。
     * @param urlName グループのチーム上での一意な名前
     * @param addGroupMemberRequest  (optional)
     * @return GroupMember
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun addGroupMembers(urlName: kotlin.String, addGroupMemberRequest: AddGroupMemberRequest? = null): HttpResponse<GroupMember> {

        val localVariableAuthNames = listOf<String>("Bearer")

        val localVariableBody = addGroupMemberRequest

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/api/v2/groups/{url_name}/members".replace("{" + "url_name" + "}", "$urlName"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * Create comment
     * 記事に対してコメントを投稿します。
     * @param itemId Article ID
     * @param createCommentRequest  (optional)
     * @return Comment
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun createComment(itemId: kotlin.String, createCommentRequest: CreateCommentRequest? = null): HttpResponse<Comment> {

        val localVariableAuthNames = listOf<String>("Bearer")

        val localVariableBody = createCommentRequest

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/api/v2/items/{item_id}/comments".replace("{" + "item_id" + "}", "$itemId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * Create group
     * 新たにグループを作成します。
     * @param createGroupRequest  (optional)
     * @return Group
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun createGroup(createGroupRequest: CreateGroupRequest? = null): HttpResponse<Group> {

        val localVariableAuthNames = listOf<String>("Bearer")

        val localVariableBody = createGroupRequest

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/api/v2/groups",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * Create imported comment
     * ユーザー名を指定して記事に対するコメントを作成します(Qiita Teamでのみ有効。管理者権限が必要)。
     * @param itemId Article ID
     * @param createImportedCommentRequest  (optional)
     * @return Comment
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun createImportedComment(itemId: kotlin.String, createImportedCommentRequest: CreateImportedCommentRequest? = null): HttpResponse<Comment> {

        val localVariableAuthNames = listOf<String>("Bearer")

        val localVariableBody = createImportedCommentRequest

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/api/v2/items/{item_id}/imported_comments".replace("{" + "item_id" + "}", "$itemId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * Create item
     * 新たに記事を作成します。  Create a new article.
     * @param createItemRequest  (optional)
     * @return Item
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun createItem(createItemRequest: CreateItemRequest? = null): HttpResponse<Item> {

        val localVariableAuthNames = listOf<String>("Bearer")

        val localVariableBody = createItemRequest

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/api/v2/items",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * Create item stock
     * 記事をストックします。
     * @param itemId Article ID
     * @return void
     */
    open suspend fun createItemStock(itemId: kotlin.String): HttpResponse<Unit> {

        val localVariableAuthNames = listOf<String>("Bearer")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.PUT,
            "/api/v2/items/{item_id}/stock".replace("{" + "item_id" + "}", "$itemId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Delete comment
     * コメントを削除します。
     * @param commentId コメントの一意なID
     * @return void
     */
    open suspend fun deleteComment(commentId: kotlin.String): HttpResponse<Unit> {

        val localVariableAuthNames = listOf<String>("Bearer")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.DELETE,
            "/api/v2/comments/{comment_id}".replace("{" + "comment_id" + "}", "$commentId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Delete group
     * グループを削除します。
     * @param urlName グループのチーム上での一意な名前
     * @return void
     */
    open suspend fun deleteGroup(urlName: kotlin.String): HttpResponse<Unit> {

        val localVariableAuthNames = listOf<String>("Bearer")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.DELETE,
            "/api/v2/groups/{url_name}".replace("{" + "url_name" + "}", "$urlName"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Delete group members
     * グループからメンバーを脱退させます。
     * @param urlName グループのチーム上での一意な名前
     * @param deleteGroupMemberRequest  (optional)
     * @return void
     */
    open suspend fun deleteGroupMembers(urlName: kotlin.String, deleteGroupMemberRequest: DeleteGroupMemberRequest? = null): HttpResponse<Unit> {

        val localVariableAuthNames = listOf<String>("Bearer")

        val localVariableBody = deleteGroupMemberRequest

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.DELETE,
            "/api/v2/groups/{url_name}/members".replace("{" + "url_name" + "}", "$urlName"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * Get item stockers
     * 記事を削除します。
     * @param itemId Article ID
     * @return void
     */
    open suspend fun deleteItem(itemId: kotlin.String): HttpResponse<Unit> {

        val localVariableAuthNames = listOf<String>("Bearer")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.DELETE,
            "/api/v2/items/{item_id}".replace("{" + "item_id" + "}", "$itemId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Delete item stock
     * 記事をストックから取り除きます。
     * @param itemId Article ID
     * @return void
     */
    open suspend fun deleteItemStock(itemId: kotlin.String): HttpResponse<Unit> {

        val localVariableAuthNames = listOf<String>("Bearer")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.DELETE,
            "/api/v2/items/{item_id}/stock".replace("{" + "item_id" + "}", "$itemId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Get authenticated user
     * アクセストークンに紐付いたユーザーを返します。
     * @return AuthenticatedUser
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getAuthenticatedUser(): HttpResponse<AuthenticatedUser> {

        val localVariableAuthNames = listOf<String>("Bearer")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v2/authenticated_user",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Get authenticated user items
     * 認証中のユーザーの記事の一覧を作成日時の降順で返します。
     * @param page ページ番号 (1から100まで) (optional)
     * @param perPage 1ページあたりに含まれる要素数 (1から100まで) (optional)
     * @return Item
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getAuthenticatedUserItems(page: kotlin.Int? = null, perPage: kotlin.Int? = null): HttpResponse<Item> {

        val localVariableAuthNames = listOf<String>("Bearer")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        page?.apply { localVariableQuery["page"] = listOf("$page") }
        perPage?.apply { localVariableQuery["per_page"] = listOf("$perPage") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v2/authenticated_user/items",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Get comment
     * コメントを取得します。
     * @param commentId コメントの一意なID
     * @return Comment
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getComment(commentId: kotlin.String): HttpResponse<Comment> {

        val localVariableAuthNames = listOf<String>("Bearer")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v2/comments/{comment_id}".replace("{" + "comment_id" + "}", "$commentId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Get group
     * グループを取得します。
     * @param urlName グループのチーム上での一意な名前
     * @return Group
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getGroup(urlName: kotlin.String): HttpResponse<Group> {

        val localVariableAuthNames = listOf<String>("Bearer")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v2/groups/{url_name}".replace("{" + "url_name" + "}", "$urlName"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Get group member
     * グループのメンバーの名前を取得します。
     * @param urlName グループのチーム上での一意な名前
     * @param userId ユーザーID
     * @return Group
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getGroupMember(urlName: kotlin.String, userId: kotlin.String): HttpResponse<Group> {

        val localVariableAuthNames = listOf<String>("Bearer")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v2/groups/{url_name}/members/{user_id}".replace("{" + "url_name" + "}", "$urlName").replace("{" + "user_id" + "}", "$userId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Get group members
     * チーム内に存在する特定のグループ一のメンバー一覧を作成日時の降順で返します。
     * @param urlName グループのチーム上での一意な名前
     * @param page ページ番号 (1から100まで) (optional)
     * @param perPage 1ページあたりに含まれる要素数 (1から100まで) (optional)
     * @return Group
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getGroupMembers(urlName: kotlin.String, page: kotlin.Int? = null, perPage: kotlin.Int? = null): HttpResponse<Group> {

        val localVariableAuthNames = listOf<String>("Bearer")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        page?.apply { localVariableQuery["page"] = listOf("$page") }
        perPage?.apply { localVariableQuery["per_page"] = listOf("$perPage") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v2/groups/{url_name}/members".replace("{" + "url_name" + "}", "$urlName"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Get groups
     * チーム内に存在するグループ一覧のうち未参加のプライベートグループ以外を作成日時の降順で返します。
     * @param page ページ番号 (1から100まで) (optional)
     * @param perPage 1ページあたりに含まれる要素数 (1から100まで) (optional)
     * @return kotlin.collections.List<Group>
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getGroups(page: kotlin.Int? = null, perPage: kotlin.Int? = null): HttpResponse<kotlin.collections.List<Group>> {

        val localVariableAuthNames = listOf<String>("Bearer")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        page?.apply { localVariableQuery["page"] = listOf("$page") }
        perPage?.apply { localVariableQuery["per_page"] = listOf("$perPage") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v2/groups",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap<GetGroupsResponse>().map { value }
    }

    @Serializable(GetGroupsResponse.Companion::class)
    private class GetGroupsResponse(val value: List<Group>) {
        companion object : KSerializer<GetGroupsResponse> {
            private val serializer: KSerializer<List<Group>> = serializer<List<Group>>()
            override val descriptor = serializer.descriptor
            override fun serialize(encoder: Encoder, value: GetGroupsResponse) = serializer.serialize(encoder, value.value)
            override fun deserialize(decoder: Decoder) = GetGroupsResponse(serializer.deserialize(decoder))
        }
    }

    /**
     * Get item
     * 記事を取得します。
     * @param itemId Article ID
     * @return Item
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getItem(itemId: kotlin.String): HttpResponse<Item> {

        val localVariableAuthNames = listOf<String>("Bearer")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v2/items/{item_id}".replace("{" + "item_id" + "}", "$itemId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Get item comments
     * 投稿に付けられたコメント一覧を投稿日時の降順で取得します。
     * @param itemId Article ID
     * @return kotlin.collections.List<Comment>
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getItemComments(itemId: kotlin.String): HttpResponse<kotlin.collections.List<Comment>> {

        val localVariableAuthNames = listOf<String>("Bearer")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v2/items/{item_id}/comments".replace("{" + "item_id" + "}", "$itemId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap<GetItemCommentsResponse>().map { value }
    }

    @Serializable(GetItemCommentsResponse.Companion::class)
    private class GetItemCommentsResponse(val value: List<Comment>) {
        companion object : KSerializer<GetItemCommentsResponse> {
            private val serializer: KSerializer<List<Comment>> = serializer<List<Comment>>()
            override val descriptor = serializer.descriptor
            override fun serialize(encoder: Encoder, value: GetItemCommentsResponse) = serializer.serialize(encoder, value.value)
            override fun deserialize(decoder: Decoder) = GetItemCommentsResponse(serializer.deserialize(decoder))
        }
    }

    /**
     * Get item stockers
     * 記事をストックしているユーザー一覧を、ストックした日時の降順で返します。
     * @param itemId Article ID
     * @param page ページ番号 (1から100まで) (optional)
     * @param perPage 1ページあたりに含まれる要素数 (1から100まで) (optional)
     * @return kotlin.collections.List<User>
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getItemStockers(itemId: kotlin.String, page: kotlin.Int? = null, perPage: kotlin.Int? = null): HttpResponse<kotlin.collections.List<User>> {

        val localVariableAuthNames = listOf<String>("Bearer")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        page?.apply { localVariableQuery["page"] = listOf("$page") }
        perPage?.apply { localVariableQuery["per_page"] = listOf("$perPage") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v2/items/{item_id}/stockers".replace("{" + "item_id" + "}", "$itemId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap<GetItemStockersResponse>().map { value }
    }

    @Serializable(GetItemStockersResponse.Companion::class)
    private class GetItemStockersResponse(val value: List<User>) {
        companion object : KSerializer<GetItemStockersResponse> {
            private val serializer: KSerializer<List<User>> = serializer<List<User>>()
            override val descriptor = serializer.descriptor
            override fun serialize(encoder: Encoder, value: GetItemStockersResponse) = serializer.serialize(encoder, value.value)
            override fun deserialize(decoder: Decoder) = GetItemStockersResponse(serializer.deserialize(decoder))
        }
    }

    /**
     * Get items
     * 記事の一覧を作成日時の降順で返します。
     * @param page ページ番号 (1から100まで) (optional)
     * @param perPage 1ページあたりに含まれる要素数 (1から100まで) (optional)
     * @param query 検索クエリ (optional)
     * @return kotlin.collections.List<Item>
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun getItems(page: kotlin.Int? = null, perPage: kotlin.Int? = null, query: kotlin.String? = null): HttpResponse<kotlin.collections.List<Item>> {

        val localVariableAuthNames = listOf<String>("Bearer")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        page?.apply { localVariableQuery["page"] = listOf("$page") }
        perPage?.apply { localVariableQuery["per_page"] = listOf("$perPage") }
        query?.apply { localVariableQuery["query"] = listOf("$query") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v2/items",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap<GetItemsResponse>().map { value }
    }

    @Serializable(GetItemsResponse.Companion::class)
    private class GetItemsResponse(val value: List<Item>) {
        companion object : KSerializer<GetItemsResponse> {
            private val serializer: KSerializer<List<Item>> = serializer<List<Item>>()
            override val descriptor = serializer.descriptor
            override fun serialize(encoder: Encoder, value: GetItemsResponse) = serializer.serialize(encoder, value.value)
            override fun deserialize(decoder: Decoder) = GetItemsResponse(serializer.deserialize(decoder))
        }
    }

    /**
     * Get OAuth team authorize
     * チーム別アクセストークンを発行するには、それぞれのチームでアプリケーションのユーザーに認可画面を表示する必要があります。ユーザーがアプリケーションからのアクセスを認可すると、アプリケーション登録時に指定されたURLにリダイレクトされます。このとき、リダイレクト先のURLクエリにcodeが付与されます。また指定した場合は state も付与されます。アプリケーションでは、この code の値を利用して POST /api/v2/team_access_tokens にリクエストを送り、チーム別アクセストークンを発行します。Qiita Teamでのみ有効です。
     * @param clientId 登録されたAPIクライアントを特定するためのIDです。40桁の16進数で表現されます。
     * @param scope アプリケーションが利用するスコープをスペース区切りで指定できます。
     * @param state CSRF対策のため、認可後にリダイレクトするURLのクエリに含まれる値を指定できます。
     * @return void
     */
    open suspend fun getOauthTeamAuthorize(clientId: kotlin.String, scope: kotlin.String, state: kotlin.String): HttpResponse<Unit> {

        val localVariableAuthNames = listOf<String>("Bearer")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        clientId?.apply { localVariableQuery["client_id"] = listOf("$clientId") }
        scope?.apply { localVariableQuery["scope"] = listOf("$scope") }
        state?.apply { localVariableQuery["state"] = listOf("$state") }
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v2/oauth/team_authorize",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Is item stock
     * 記事をストックしているかどうかを調べます。
     * @param itemId Article ID
     * @return void
     */
    open suspend fun isItemStock(itemId: kotlin.String): HttpResponse<Unit> {

        val localVariableAuthNames = listOf<String>("Bearer")

        val localVariableBody = 
            io.ktor.client.utils.EmptyContent

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.GET,
            "/api/v2/items/{item_id}/stock".replace("{" + "item_id" + "}", "$itemId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return request(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }


    /**
     * Update comment
     * コメントを更新します。
     * @param commentId コメントの一意なID
     * @param updateCommentRequest  (optional)
     * @return Comment
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun updateComment(commentId: kotlin.String, updateCommentRequest: UpdateCommentRequest? = null): HttpResponse<Comment> {

        val localVariableAuthNames = listOf<String>("Bearer")

        val localVariableBody = updateCommentRequest

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.PATCH,
            "/api/v2/comments/{comment_id}".replace("{" + "comment_id" + "}", "$commentId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * Update group
     * グループを更新します。
     * @param urlName グループのチーム上での一意な名前
     * @param updateGroupRequest  (optional)
     * @return Group
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun updateGroup(urlName: kotlin.String, updateGroupRequest: UpdateGroupRequest? = null): HttpResponse<Group> {

        val localVariableAuthNames = listOf<String>("Bearer")

        val localVariableBody = updateGroupRequest

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.PATCH,
            "/api/v2/groups/{url_name}".replace("{" + "url_name" + "}", "$urlName"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



    /**
     * 
     * 記事を更新します。
     * @param itemId Article ID
     * @param updateItemRequest  (optional)
     * @return Item
     */
    @Suppress("UNCHECKED_CAST")
    open suspend fun updateItem(itemId: kotlin.String, updateItemRequest: UpdateItemRequest? = null): HttpResponse<Item> {

        val localVariableAuthNames = listOf<String>("Bearer")

        val localVariableBody = updateItemRequest

        val localVariableQuery = mutableMapOf<String, List<String>>()
        val localVariableHeaders = mutableMapOf<String, String>()

        val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.PATCH,
            "/api/v2/items/{item_id}".replace("{" + "item_id" + "}", "$itemId"),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
        )

        return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
        ).wrap()
    }



}
